module.exports = {
  apps: [
    {
      name: 'fixdev-erp',
      cwd: '/data/fixdev',
      script: 'dist/server.cjs',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_restarts: 20,
      min_uptime: '30s',
      restart_delay: 3000,
      exp_backoff_restart_delay: 2000,
      max_memory_restart: '500M',
      kill_timeout: 10000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        FIXDEV_PROFILE: 'production',
        FIXDEV_DATABASE_NAME: 'fixdev',
        PORT: 3000,
        APP_URL: 'https://fixdev.web.id',
        ALLOWED_ORIGINS: 'https://fixdev.web.id,https://www.fixdev.web.id',
        TENANT_ROOT_DOMAIN: 'fixdev.web.id',
        ALLOW_DEV_API_TOKENS: 'false',
        DOTENV_CONFIG_PATH: '/etc/fixdev/fixdev.production.env',
      },
      error_file: '/data/fixdev/logs/prod.err.log',
      out_file: '/data/fixdev/logs/prod.out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'fixdev-dev',
      cwd: '/data/fixdev',
      script: 'node_modules/.bin/tsx',
      args: 'server.ts',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_restarts: 20,
      min_uptime: '30s',
      restart_delay: 3000,
      exp_backoff_restart_delay: 2000,
      max_memory_restart: '500M',
      kill_timeout: 10000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: 'development',
        FIXDEV_PROFILE: 'development',
        FIXDEV_DATABASE_NAME: 'fixdev_dev',
        JWT_SECRET: 'fixdev_jwt_secret_2026_min_32_chars_secure',
        ADMIN_TOKEN: 'fixdev_admin_token_2026_secure',
        PORT: 3001,
        DEV_PORT: 3001,
        APP_URL: 'https://dev.fixdev.web.id',
        ALLOWED_ORIGINS: 'https://dev.fixdev.web.id,http://localhost:3001,http://localhost:5173',
        TENANT_ROOT_DOMAIN: 'fixdev.web.id',
        ALLOW_DEV_API_TOKENS: 'false',
        DOTENV_CONFIG_PATH: '/data/fixdev/.env.dev',
      },
      error_file: '/data/fixdev/logs/dev.err.log',
      out_file: '/data/fixdev/logs/dev.out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
