ALTER TABLE superadmin_audit_events ALTER COLUMN effective_tenant_id DROP NOT NULL;

INSERT INTO superadmin_role_permissions(role, permission) VALUES
  ('ROOT_ADMIN', 'billing:manage_plans'),
  ('ROOT_ADMIN', 'billing:view_config'),
  ('ROOT_ADMIN', 'billing:manage_config'),
  ('ROOT_ADMIN', 'billing:view_manual_payments'),
  ('ROOT_ADMIN', 'billing:manage_manual_payments'),
  ('ROOT_ADMIN', 'billing:view_plans'),
  ('ROOT_ADMIN', 'tenants:view_all'),
  ('ROOT_ADMIN', 'tenants:view_detail'),
  ('ROOT_ADMIN', 'tenants:view_invitations'),
  ('ROOT_ADMIN', 'impersonation:create_session'),
  ('ROOT_ADMIN', 'impersonation:end_session'),
  ('ROOT_ADMIN', 'audit:view_all'),
  ('ROOT_ADMIN', 'permissions:view_roles'),
  ('ROOT_ADMIN', 'permissions:manage_roles'),
  ('ROOT_ADMIN', 'users:view_superadmin_users'),
  ('ROOT_ADMIN', 'incidents:view_all'),
  ('ROOT_ADMIN', 'incidents:manage_incidents'),
  ('SUPPORT_ADMIN', 'tenants:view_all'),
  ('SUPPORT_ADMIN', 'tenants:view_detail'),
  ('SUPPORT_ADMIN', 'tenants:view_invitations'),
  ('SUPPORT_ADMIN', 'impersonation:create_session'),
  ('SUPPORT_ADMIN', 'impersonation:end_session'),
  ('BILLING_ADMIN', 'billing:view_plans'),
  ('BILLING_ADMIN', 'billing:view_config'),
  ('BILLING_ADMIN', 'billing:view_manual_payments'),
  ('BILLING_ADMIN', 'billing:manage_manual_payments'),
  ('OPERATIONS_ADMIN', 'platform:view_bootstrap'),
  ('OPERATIONS_ADMIN', 'platform:manage_storage'),
  ('OPERATIONS_ADMIN', 'platform:view_backups'),
  ('OPERATIONS_ADMIN', 'platform:manage_backups'),
  ('OPERATIONS_ADMIN', 'platform:view_notifications'),
  ('OPERATIONS_ADMIN', 'platform:manage_notifications'),
  ('OPERATIONS_ADMIN', 'platform:view_outbox'),
  ('OPERATIONS_ADMIN', 'platform:view_alerts'),
  ('OPERATIONS_ADMIN', 'platform:manage_alerts'),
  ('OPERATIONS_ADMIN', 'operations:run_cron'),
  ('OPERATIONS_ADMIN', 'incidents:view_all'),
  ('OPERATIONS_ADMIN', 'incidents:manage_incidents'),
  ('SECURITY_ADMIN', 'audit:view_all'),
  ('SECURITY_ADMIN', 'permissions:view_roles'),
  ('SECURITY_ADMIN', 'permissions:manage_roles'),
  ('SECURITY_ADMIN', 'users:view_superadmin_users'),
  ('SECURITY_ADMIN', 'users:assign_role')
ON CONFLICT DO NOTHING;
