import React, { useEffect, useState } from "react";
import { AlertTriangle, BellRing, CheckCircle2, RefreshCw, ServerCrash } from "lucide-react";
import { useSaaS } from "../../context/SaaSContext";
import { useToast } from "../ui/Toast";
import { readJsonResponse } from "../../utils/apiResponse";

export default function OperationsCenter({ readOnlyMode = false }: { readOnlyMode?: boolean }) {
  const { apiFetch, platformHealth, refreshPlatformHealth } = useSaaS();
  const { showToast } = useToast();
  const [notifications, setNotifications] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [alertSettings, setAlertSettings] = useState({ overdueEnabled: true, trialDays: 7, queueFailureEnabled: true, dailyReportHour: 8 });
  const [outboxItems, setOutboxItems] = useState<any[]>([]);
  const [incidentItems, setIncidentItems] = useState<any[]>([]);

  const load = async () => {
    setLoading(true);
    try {
      const [notificationResponse, settingsResponse, outboxResponse, incidentResponse] = await Promise.all([
        apiFetch("/api/superadmin/notifications"),
        apiFetch("/api/superadmin/alert-settings"),
        apiFetch("/api/superadmin/outbox"),
        apiFetch("/api/superadmin/incidents"),
      ]);
      const data = await readJsonResponse<any>(notificationResponse, "Notifikasi operasional");
      const settingsData = await readJsonResponse<any>(settingsResponse, "Pengaturan alert");
      const outboxData = await readJsonResponse<any>(outboxResponse, "Antrean notifikasi");
      const incidentData = await readJsonResponse<any>(incidentResponse, "Insiden platform");
      setNotifications(data.notifications || []);
      setOutboxItems(outboxData.items || []);
      setIncidentItems(incidentData.incidents || []);
      setAlertSettings(settingsData.settings || alertSettings);
      await refreshPlatformHealth();
    } finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);

  const outbox = platformHealth.components?.notificationOutbox;
  const incidents = platformHealth.components?.incidents;
  return <div className="space-y-6">
    <section className="grid grid-cols-1 gap-4 md:grid-cols-3">
      <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><p className="text-xs font-bold text-slate-500">Antrean Notifikasi</p><p className="mt-2 text-2xl font-black">{outbox?.pending ?? 0}</p><p className="text-xs text-slate-400">{outbox?.failed ?? 0} gagal</p></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><p className="text-xs font-bold text-slate-500">Insiden Aktif</p><p className="mt-2 text-2xl font-black">{incidents?.open ?? 0}</p><p className="text-xs text-slate-400">{incidents?.critical ?? 0} kritis</p></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><p className="text-xs font-bold text-slate-500">Status Platform</p><p className={`mt-2 text-2xl font-black ${platformHealth.status === "ok" ? "text-emerald-600" : "text-amber-600"}`}>{platformHealth.status.toUpperCase()}</p><div className="mt-2 flex gap-3"><button type="button" onClick={load} className="inline-flex items-center gap-1 text-xs font-bold text-indigo-600"><RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} /> Periksa ulang</button><button type="button" disabled={readOnlyMode} onClick={async () => { const result = await readJsonResponse<any>(await apiFetch('/api/superadmin/storage/collect',{method:'POST'}),'Ukur storage'); showToast(`${result.measured} tenant berhasil diukur.`, "success"); await load(); }} className="text-xs font-bold text-indigo-600 disabled:opacity-40">Ukur storage</button></div></article>
    </section>
    <section className="grid grid-cols-1 gap-6 lg:grid-cols-2">
      <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h3 className="text-sm font-black">Pengaturan Alert Terjadwal</h3><div className="mt-4 grid gap-3"><label className="flex items-center justify-between text-xs"><span>Peringatan invoice overdue</span><input type="checkbox" checked={alertSettings.overdueEnabled} onChange={(event) => setAlertSettings({ ...alertSettings, overdueEnabled: event.target.checked })} /></label><label className="text-xs">Peringatan trial (hari sebelum berakhir)<input type="number" min={1} max={30} value={alertSettings.trialDays} onChange={(event) => setAlertSettings({ ...alertSettings, trialDays: Number(event.target.value) })} className="mt-1 w-full rounded-xl border border-slate-200 p-2 dark:border-zinc-700 dark:bg-zinc-950" /></label><label className="flex items-center justify-between text-xs"><span>Peringatan antrean gagal</span><input type="checkbox" checked={alertSettings.queueFailureEnabled} onChange={(event) => setAlertSettings({ ...alertSettings, queueFailureEnabled: event.target.checked })} /></label><label className="text-xs">Jam laporan harian<input type="number" min={0} max={23} value={alertSettings.dailyReportHour} onChange={(event) => setAlertSettings({ ...alertSettings, dailyReportHour: Number(event.target.value) })} className="mt-1 w-full rounded-xl border border-slate-200 p-2 dark:border-zinc-700 dark:bg-zinc-950" /></label><button type="button" disabled={readOnlyMode} onClick={async () => { await readJsonResponse(await apiFetch('/api/superadmin/alert-settings',{method:'PUT',headers:{'X-SuperAdmin-Mode':readOnlyMode?'read-only':'edit'},body:JSON.stringify(alertSettings)}),'Simpan alert'); }} className="rounded-xl bg-indigo-600 py-2.5 text-xs font-bold text-white disabled:opacity-40">Simpan pengaturan alert</button></div></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h3 className="text-sm font-black">Kebijakan Retry</h3><p className="mt-2 text-xs leading-relaxed text-slate-500">Antrean berstatus FAILED dapat dikembalikan ke PENDING oleh Operations Admin. Attempts dan last error direset, kemudian worker mengambil pekerjaan pada siklus berikutnya. Semua retry dicatat di audit.</p><div className="mt-4 rounded-xl bg-slate-50 p-4 text-xs dark:bg-zinc-950"><b>Status saat ini</b><p className="mt-1">Pending: {outbox?.pending || 0} · Failed: {outbox?.failed || 0}</p></div></article>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h3 className="text-sm font-black">Insiden Platform</h3><div className="mt-4 space-y-2">{incidentItems.length ? incidentItems.map((item) => <div key={item.id} className="rounded-xl border border-slate-200 p-3 text-xs dark:border-zinc-800"><div className="flex items-start justify-between gap-3"><span><b>{item.title}</b><span className="ml-2 text-slate-500">{item.component} · {item.severity}</span><p className="mt-1 text-slate-500">{item.details || "Tanpa detail"}</p></span><span className="font-bold">{item.status}</span></div><div className="mt-3 flex flex-wrap gap-2">{item.status === "OPEN" && !item.acknowledged_at && <button disabled={readOnlyMode} onClick={async () => { await readJsonResponse(await apiFetch(`/api/superadmin/incidents/${item.id}/actions`, { method: "POST", body: JSON.stringify({ action: "ACKNOWLEDGE" }) }), "Acknowledge insiden"); await load(); }} className="rounded-lg bg-amber-500 px-2 py-1 font-bold text-white disabled:opacity-40">Acknowledge</button>}{item.status === "OPEN" && <button disabled={readOnlyMode} onClick={async () => { const note = window.prompt("Catatan penyelesaian insiden:") || ""; if (!note.trim()) return; await readJsonResponse(await apiFetch(`/api/superadmin/incidents/${item.id}/actions`, { method: "POST", body: JSON.stringify({ action: "RESOLVE", note }) }), "Selesaikan insiden"); await load(); }} className="rounded-lg bg-emerald-600 px-2 py-1 font-bold text-white disabled:opacity-40">Resolve</button>}{item.status === "RESOLVED" && <button disabled={readOnlyMode} onClick={async () => { await readJsonResponse(await apiFetch(`/api/superadmin/incidents/${item.id}/actions`, { method: "POST", body: JSON.stringify({ action: "REOPEN" }) }), "Buka ulang insiden"); await load(); }} className="rounded-lg bg-indigo-600 px-2 py-1 font-bold text-white disabled:opacity-40">Reopen</button>}</div>{item.timeline?.length > 0 && <p className="mt-2 text-[10px] text-slate-400">{item.timeline.length} aktivitas tercatat</p>}</div>) : <p className="py-8 text-center text-sm text-slate-500">Belum ada insiden tercatat.</p>}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h3 className="text-sm font-black">Antrean Delivery</h3><div className="mt-4 max-h-80 space-y-2 overflow-y-auto">{outboxItems.length ? outboxItems.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-xs dark:border-zinc-800"><span><b>{item.event_key}</b><br/><span className="text-slate-500">{item.channel} · {item.recipient || 'internal'} · attempts {item.attempts}</span>{item.lastError && <span className="block text-rose-500">{item.lastError}</span>}</span><span className="text-right"><b>{item.status}</b>{item.status === 'FAILED' && <button type="button" disabled={readOnlyMode} onClick={async () => { await readJsonResponse(await apiFetch(`/api/superadmin/outbox/${item.id}/retry`,{method:'POST',headers:{'X-SuperAdmin-Mode':readOnlyMode?'read-only':'edit'}}),'Retry antrean'); await load(); }} className="mt-1 block rounded-lg bg-indigo-600 px-2 py-1 text-[10px] font-bold text-white disabled:opacity-40">Retry</button>}</span></div>) : <p className="py-8 text-center text-sm text-slate-500">Antrean kosong.</p>}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h3 className="flex items-center gap-2 text-sm font-black"><BellRing className="h-4 w-4" /> Aktivitas Notifikasi</h3><div className="mt-4 space-y-2">{notifications.length ? notifications.map((item) => <div key={item.id} className="flex items-start justify-between rounded-xl border border-slate-200 p-3 text-xs dark:border-zinc-800"><span className="flex gap-2">{item.read_at ? <CheckCircle2 className="h-4 w-4 text-emerald-500" /> : <AlertTriangle className="h-4 w-4 text-amber-500" />}<span><b>{item.title}</b><br/><span className="text-slate-500">{item.message}</span></span></span><span className="text-slate-400">{new Date(item.created_at).toLocaleString("id-ID")}</span></div>) : <div className="py-10 text-center text-sm text-slate-500"><ServerCrash className="mx-auto mb-2 h-8 w-8 text-slate-300" />Belum ada aktivitas notifikasi.</div>}</div></section>
  </div>;
}
