export const CATEGORY_CONFIGS: Record<
  string,
  {
    checklist: string[];
    accessories: { id: string; label: string }[];
  }
> = {
  Smartphone: {
    checklist: [
      "Unit Menyala (Power On)",
      "Layar / LCD (No Dead Pixel)",
      "Touchscreen Berfungsi Baik",
      "Tombol Power & Volume",
      "Port Charger & Konektor USB",
      "Kamera Depan & Belakang",
      "Speaker & Mikrofon",
      "Wi-Fi & Sinyal Seluler",
      "Baterai Sehat / Tidak Kembung",
      "Sensor Sidik Jari / Face ID",
    ],
    accessories: [
      { id: "charger", label: "🔌 Charger / Adaptor" },
      { id: "cable", label: "🔌 Kabel Data" },
      { id: "sim", label: "📱 Kartu SIM" },
      { id: "case", label: "🛡️ Softcase / Hardcase" },
      { id: "box", label: "📦 Dus / Box" },
    ],
  },
  Tablet: {
    checklist: [
      "Unit Menyala (Power On)",
      "Layar / LCD (No Dead Pixel)",
      "Touchscreen Berfungsi Baik",
      "Tombol Power & Volume",
      "Port Charger & Konektor USB",
      "Kamera Depan & Belakang",
      "Speaker & Mikrofon",
      "Wi-Fi / Bluetooth Sinyal",
      "Baterai Sehat / Tidak Kembung",
      "Fungsi Stylus / Pen (Jika Ada)",
    ],
    accessories: [
      { id: "charger", label: "🔌 Charger / Adaptor" },
      { id: "cable", label: "🔌 Kabel Data" },
      { id: "stylus", label: "✏️ Stylus / S-Pen" },
      { id: "keyboard_case", label: "⌨️ Keyboard Case" },
      { id: "case", label: "🛡️ Softcase / Hardcase" },
      { id: "box", label: "📦 Dus / Box" },
    ],
  },
  Laptop: {
    checklist: [
      "Unit Menyala (Power On)",
      "Layar / LCD (No Flickering)",
      "Keyboard / Tombol Semua Berfungsi",
      "Touchpad / Trackpad Normal",
      "Baterai Mengisi & Awet",
      "Port USB / Type-C / HDMI",
      "Speaker, Jack Audio & Mic",
      "Wi-Fi & Bluetooth Koneksi",
      "Kamera / Webcam",
      "Engsel Layar Kokoh",
      "Sistem Pendingin / Kipas Berputar",
    ],
    accessories: [
      { id: "charger", label: "🔌 Charger / Adaptor Laptop" },
      { id: "cable", label: "🔌 Kabel Power" },
      { id: "mouse", label: "🖱️ Mouse (Wired/Wireless)" },
      { id: "bag", label: "💼 Tas Laptop" },
      { id: "keyboard_protector", label: "⌨️ Pelindung Keyboard" },
      { id: "box", label: "📦 Dus / Box" },
    ],
  },
  Desktop: {
    checklist: [
      "Unit Menyala (Power On)",
      "Port Display (HDMI/VGA/DP)",
      "Semua Port USB & Audio Jack",
      "Kipas Processor & Casing Aktif",
      "Suhu Processor Normal (Tidak Overheat)",
      "RAM & Storage Terbaca Sesuai",
      "Wi-Fi Card / LAN Port Normal",
      "Power Supply (PSU) Stabil",
      "Sistem Operasi Booting Lancar",
    ],
    accessories: [
      { id: "power_cable", label: "🔌 Kabel Power CPU" },
      { id: "keyboard", label: "⌨️ Keyboard" },
      { id: "mouse", label: "🖱️ Mouse" },
      { id: "hdmi_cable", label: "🔌 Kabel HDMI/VGA" },
      { id: "wifi_dongle", label: "📶 Dongle Wi-Fi" },
      { id: "adapter", label: "🔌 Power Adapter Eksternal" },
    ],
  },
  Console: {
    checklist: [
      "Unit Menyala (Power On)",
      "Port Display (HDMI/VGA/DP)", // Fixed duplicate check name bug: was "Port HDMI / Display Out", unified display checks
      "Pembaca Kaset / Blu-Ray Drive",
      "Konektivitas Controller / Sync",
      "Sistem Pendingin / Kipas",
      "Wi-Fi & Koneksi Internet",
      "Suhu & Suara Mesin Halus",
      "Penyimpanan Internal Terbaca",
    ],
    accessories: [
      { id: "controller", label: "🎮 Controller / Stik Game" },
      { id: "power_cable", label: "🔌 Kabel Power / Adaptor" },
      { id: "hdmi_cable", label: "🔌 Kabel HDMI" },
      { id: "dock", label: "📺 Docking Station" },
      { id: "game_disc", label: "💿 Kaset / Game Disc" },
      { id: "box", label: "📦 Dus / Box" },
    ],
  },
  Wearable: {
    checklist: [
      "Unit Menyala (Power On)",
      "Layar Sentuh (Touchscreen) Responsif",
      "Sensor Detak Jantung / Kesehatan",
      "Koneksi Bluetooth ke HP",
      "Tombol Fisik Berfungsi",
      "Port Charger / Wireless Charging",
      "Baterai Mengisi Normal",
      "Sistem Getar (Vibration)",
    ],
    accessories: [
      { id: "charger", label: "🔌 Charger / Magnetic Dock" },
      { id: "cable", label: "🔌 Kabel Data" },
      { id: "strap", label: "⌚ Strap / Tali Cadangan" },
      { id: "box", label: "📦 Dus / Box" },
    ],
  },
  Printer: {
    checklist: [
      "Unit Menyala (Power On)",
      "Roller Penarik Kertas (Paper Feed)",
      "Sensor Kertas (Paper Sensor)",
      "Print Head / Cartridge Normal",
      "Kualitas Cetak (No Clogging/Smudge)",
      "Scanner Bed / ADF (Jika Ada)",
      "Koneksi USB / Wi-Fi",
      "Mekanik Ink Carriage / Belt",
    ],
    accessories: [
      { id: "power_cable", label: "🔌 Kabel Power / Adaptor" },
      { id: "usb_cable", label: "🔌 Kabel USB Printer" },
      { id: "cartridge_black", label: "🖨️ Cartridge Hitam (Black)" },
      { id: "cartridge_color", label: "🖨️ Cartridge Warna (Color)" },
      { id: "ink_bottles", label: "🫙 Botol Tinta / Tank" },
      { id: "box", label: "📦 Dus / Box" },
    ],
  },
  Other: {
    checklist: [
      "Unit Menyala (Power On)",
      "Fisik Luar Utuh & Bagus",
      "Fungsi Utama Berjalan Normal",
      "Port Input & Output Stabil",
      "Tombol Kontrol Responsif",
    ],
    accessories: [
      { id: "charger", label: "🔌 Charger / Adaptor" },
      { id: "cable", label: "🔌 Kabel Konektor" },
      { id: "battery", label: "🔋 Baterai Tambahan" },
      { id: "remote", label: "🕹️ Remote Control" },
      { id: "bag", label: "💼 Tas / Softcase" },
      { id: "box", label: "📦 Dus / Box" },
    ],
  },
};
