import type { NextFunction, Request, Response } from "express";
import type { PoolClient } from "pg";
import { z } from "zod";
import { dbQuery, dbTransaction } from "../../lib/db.js";
import { logger } from "../../lib/logger.js";
import { toApiResponse } from "../utils/responseTransform.js";

const text = (max: number) => z.string().trim().max(max);
const bool = z.boolean();
const money = z.number().finite().min(0).max(100_000_000);
const hex = z.string().regex(/^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/);
const httpsUrl = z.string().trim().max(2048).refine((value) => !value || (() => { try { return new URL(value).protocol === "https:"; } catch { return false; } })(), "URL harus HTTPS");
const secret = z.string().max(4096).optional();
const templateSchema = z.object({ id: text(100), name: text(150), category: z.enum(["SERVICE_UPDATE", "INVOICE_REMINDER", "PROMOTION", "CUSTOM"]), content: z.string().max(10_000) }).strict();
const schemas = {
  branding: z.object({ primaryColor: hex.optional(), secondaryColor: hex.optional(), accentColor: hex.optional(), logoUrl: httpsUrl.optional(), slogan: text(250).optional(), fontFamily: text(50).optional(), customDomain: text(253).optional(), portalHelpTitle: text(150).optional(), portalContactText: text(1000).optional(), whiteLabelEnabled: bool.optional() }).strict(),
  generalSettings: z.object({ appName: text(150).optional(), timezone: text(100).optional(), dateFormat: text(30).optional(), language: text(10).optional(), numberFormat: text(30).optional(), maintenanceMode: bool.optional() }).strict(),
  serviceSettings: z.object({ defaultDiagnosisFee: money.optional(), requireEstimateApproval: bool.optional(), allowProceedWithoutApproval: bool.optional(), slaHours: z.number().int().min(1).max(720).optional(), autoAssignTechnician: bool.optional() }).strict(),
  posSettings: z.object({ paymentMethods: z.array(text(50)).max(30).optional(), maxDiscount: z.number().min(0).max(100).optional(), allowNegativeStock: bool.optional(), requireVoidApproval: bool.optional(), requireCloseCash: bool.optional() }).strict(),
  inventorySettings: z.object({ hppMethod: z.enum(["FIFO", "LIFO", "AVG"]).optional(), defaultWarehouseId: z.string().uuid().optional(), requireAdjustmentApproval: bool.optional(), enableStockAlert: bool.optional() }).strict(),
  accountingSettings: z.object({ defaultCashAccountId: text(100).optional(), defaultBankAccountId: text(100).optional(), defaultSalesAccountId: text(100).optional(), defaultHppAccountId: text(100).optional(), defaultInventoryAccountId: text(100).optional(), defaultReceivableAccountId: text(100).optional(), defaultPayableAccountId: text(100).optional(), autoJournalEnabled: bool.optional() }).strict(),
  hrmSettings: z.object({ defaultWorkHours: z.number().min(1).max(24).optional(), graceLateMinutes: z.number().int().min(0).max(1440).optional(), enableOvertime: bool.optional(), overtimeRate: z.number().min(1).max(10).optional() }).strict(),
  portalSettings: z.object({ enableStatusCheck: bool.optional(), enableEstimateApproval: bool.optional(), enableInvoiceView: bool.optional(), enableWarrantyView: bool.optional(), enableTicketTracking: bool.optional(), hideInternalNotes: bool.optional(), hideProfit: bool.optional() }).strict(),
  emailSettings: z.object({ smtpHost: text(253).optional(), smtpPort: z.number().int().min(1).max(65535).optional(), smtpUser: text(320).optional(), smtpPass: secret, defaultFromEmail: z.union([z.literal(""), z.string().email().max(320)]).optional(), enablePushNotifications: bool.optional(), enableRealtimeNotifications: bool.optional() }).strict(),
  uploadSettings: z.object({ maxUploadSizeMb: z.number().int().min(1).max(100).optional(), allowedFileTypes: text(1000).optional(), folderInvoices: text(250).optional(), folderServicePhotos: text(250).optional(), folderAttendance: text(250).optional(), folderCustomerDocs: text(250).optional(), fileVisibility: z.enum(["private", "public"]).optional(), retentionDays: z.number().int().min(30).max(3650).optional() }).strict(),
  themeSettings: z.object({ logo: httpsUrl.optional(), primaryColor: hex.optional(), secondaryColor: hex.optional(), darkMode: bool.optional(), sidebarMode: z.enum(["collapsed", "expanded"]).optional(), layoutDensity: z.enum(["compact", "comfortable", "spacious"]).optional() }).strict(),
  securitySettings: z.object({ sessionTimeout: z.number().int().min(15).max(480).optional(), minPasswordLength: z.number().int().min(6).max(32).optional(), requireUppercase: bool.optional(), requireNumber: bool.optional(), requireSpecial: bool.optional(), maxLoginAttempts: z.number().int().min(1).max(20).optional(), lockoutDuration: z.number().int().min(1).max(1440).optional(), enableMFA: bool.optional(), allowPasswordReuse: bool.optional() }).strict(),
  notificationSettings: z.object({ whatsappEnabled: bool.optional(), telegramEnabled: bool.optional(), emailEnabled: bool.optional(), whatsappNumber: text(30).optional(), telegramBotToken: secret, telegramChatId: text(100).optional() }).strict(),
  printConfig: z.object({ printMode: z.enum(["browser", "qz"]).optional(), printerName: text(250).optional(), paperSize: text(50).optional(), printQrCode: bool.optional(), printHeaderLogo: bool.optional(), printCustomerNotes: bool.optional(), printTermsAndConditions: bool.optional(), showTermsInTracking: bool.optional(), printFontSize: text(20).optional(), printMargin: z.number().min(0).max(100).optional(), customHeaderTitle: text(250).optional(), customFooterText: text(1000).optional(), termsAndConditionsText: z.string().max(20_000).optional(), labelWidth: z.number().min(20).max(600).optional(), labelHeight: z.number().min(20).max(400).optional(), labelFontSize: text(20).optional(), labelShowQr: bool.optional(), labelShowLogo: bool.optional(), labelCustomText: text(1000).optional(), termsSalesText: z.string().max(20_000).optional(), termsRentalText: z.string().max(20_000).optional() }).strict(),
  waConfig: z.object({ gateway: text(100).optional(), isConnected: bool.optional(), apiToken: secret, phoneNumber: text(30).optional(), sendingMethod: z.enum(["API", "MANUAL"]).optional(), syncEstimate: bool.optional(), phoneId: text(100).optional(), wabaId: text(100).optional(), webhookSecret: secret, whatsappKey: secret, callbackUrl: httpsUrl.optional(), triggers: z.record(z.string().max(100), bool).optional(), templates: z.array(templateSchema).max(200).optional() }).strict(),
  moduleConfigs: z.record(z.string().trim().min(1).max(100), z.object({ enabled: bool.optional() }).strict()).refine((value) => Object.keys(value).length <= 100),
} satisfies Record<string, z.ZodType>;

export type SettingsDomain = keyof typeof schemas;
export function validateSettingsDomain(domain: string, value: unknown) { const schema = schemas[domain as SettingsDomain]; return schema ? schema.safeParse(value) : { success: false as const }; }
const roleSchema = z.enum(["OWNER", "ADMIN", "MANAGER", "KASIR", "TEKNISI", "SALES", "HR"]);
const permissionsSchema = z.array(z.string().trim().min(1).max(100)).max(200);
const rbacSchema = z.object({ expectedVersion: z.number().int().positive(), matrix: z.record(roleSchema, permissionsSchema) }).strict();
const userRbacSchema = z.object({ role: roleSchema, permissions: permissionsSchema }).strict();
const branchSchema = z.object({ id: z.string().uuid().optional(), name: text(150).min(1), address: text(500).default(""), phone: text(50).default(""), isActive: bool.default(true) }).strict();
const MASK = /^(?:\*+|•+|x+)$/i;
const SECRET_FIELDS: Partial<Record<SettingsDomain, string[]>> = { emailSettings: ["smtpPass"], notificationSettings: ["telegramBotToken"], waConfig: ["apiToken", "webhookSecret", "whatsappKey"] };
export function mergeSettingsSecrets(domain: SettingsDomain, existing: Record<string, unknown>, incoming: Record<string, unknown>) { const merged = { ...existing, ...incoming }; for (const field of SECRET_FIELDS[domain] || []) { const value = incoming[field]; if (value === undefined || typeof value === "string" && (!value.trim() || MASK.test(value.trim()))) { if (existing[field] === undefined) delete merged[field]; else merged[field] = existing[field]; } } return merged; }

export async function updateSettingsDomain(req: Request, res: Response) {
  const expectedVersion = z.number().int().positive().safeParse(req.body?.expectedVersion);
  const parsed = validateSettingsDomain(req.params.domain, req.body?.value);
  if (!expectedVersion.success || !parsed.success) return res.status(422).json({ error: "Domain atau payload pengaturan tidak valid." });
  const domain = req.params.domain as SettingsDomain;
  try {
    const result = await dbTransaction(async (client) => {
      const current = await client.query(`SELECT settings,branding,version FROM tenants WHERE id=$1 FOR UPDATE`, [req.tenantId]);
      const tenant = current.rows[0];
      if (!tenant || tenant.version !== expectedVersion.data) return null;
      const existing = domain === "branding" ? tenant.branding || {} : tenant.settings?.[domain] || {};
      const value = mergeSettingsSecrets(domain, existing, parsed.data as Record<string, unknown>);
      return client.query(domain === "branding" ? `UPDATE tenants SET branding=$3::jsonb,version=version+1 WHERE id=$1 AND version=$2 RETURNING settings,branding,version` : `UPDATE tenants SET settings=jsonb_set(COALESCE(settings,'{}'::jsonb),$3::text[],$4::jsonb,true),version=version+1 WHERE id=$1 AND version=$2 RETURNING settings,branding,version`, domain === "branding" ? [req.tenantId, expectedVersion.data, JSON.stringify(value)] : [req.tenantId, expectedVersion.data, [domain], JSON.stringify(value)]);
    });
    if (!result?.rows[0]) return res.status(409).json({ error: "Pengaturan telah berubah. Muat ulang halaman.", code: "VERSION_CONFLICT" });
    res.json(toApiResponse(result.rows[0]));
  } catch (err: any) { logger.error({ err: err.message, tenantId: req.tenantId, domain }, "Settings update failed"); res.status(500).json({ error: "Pengaturan gagal disimpan." }); }
}

export async function updateRbacMatrix(req: Request, res: Response) { const body = rbacSchema.safeParse(req.body); if (!body.success) return res.status(422).json({ error: "Matriks RBAC atau versi tidak valid." }); try { const result = await dbQuery(`UPDATE tenants SET rbac_matrix=$3::jsonb,version=version+1 WHERE id=$1 AND version=$2 RETURNING rbac_matrix,version`, [req.tenantId, body.data.expectedVersion, JSON.stringify(body.data.matrix)]); if (!result.rows[0]) return res.status(409).json({ error: "RBAC telah berubah. Muat ulang halaman.", code: "VERSION_CONFLICT" }); res.json(toApiResponse(result.rows[0])); } catch (err: any) { logger.error({ err: err.message, tenantId: req.tenantId }, "RBAC matrix update failed"); res.status(500).json({ error: "Matriks RBAC gagal disimpan." }); } }
export async function updateUserRbac(req: Request, res: Response) { const body = userRbacSchema.safeParse(req.body); if (!body.success) return res.status(422).json({ error: "Role atau permissions tidak valid." }); if (req.params.userId === req.authActor?.userId && body.data.role !== req.authActor.role) return res.status(422).json({ error: "Role akun sendiri tidak dapat diubah." }); try { const result = await dbQuery(`UPDATE users SET role=$3,permissions=$4::text[] WHERE id=$1 AND tenant_id=$2 RETURNING id,role,permissions`, [req.params.userId, req.tenantId, body.data.role, body.data.permissions]); if (!result.rows[0]) return res.status(404).json({ error: "Pengguna tidak ditemukan." }); res.json(toApiResponse(result.rows[0])); } catch (err: any) { logger.error({ err: err.message, tenantId: req.tenantId }, "User RBAC update failed"); res.status(500).json({ error: "RBAC pengguna gagal disimpan." }); } }
export async function createBranch(req: Request, res: Response) { const body = branchSchema.safeParse(req.body); if (!body.success) return res.status(422).json({ error: "Data cabang tidak valid." }); try { const result = await dbTransaction(async (client) => { const tenantResult = await client.query(`SELECT tier,settings FROM tenants WHERE id=$1 FOR UPDATE`, [req.tenantId]); const tenant = tenantResult.rows[0]; if (!tenant) return { code: 404, error: "Tenant tidak ditemukan." }; const countResult = await client.query(`SELECT COUNT(*)::int AS count FROM branches WHERE tenant_id=$1`, [req.tenantId]); const tierLimits: Record<string, number> = { BASIC: 1, PRO: 5, ENTERPRISE: 20 }; const limit = Number(tenant.settings?.limits?.branches ?? tierLimits[tenant.tier] ?? 1); const count = countResult.rows[0].count; if (count >= limit) return { code: 409, error: `Kuota cabang penuh (${count}/${limit}).`, errorCode: "BRANCH_QUOTA_EXCEEDED" }; const branch = await client.query(`INSERT INTO branches(id,tenant_id,name,address,phone,is_active) VALUES (COALESCE($1::uuid,gen_random_uuid()),$2,$3,$4,$5,$6) RETURNING *`, [body.data.id || null, req.tenantId, body.data.name, body.data.address, body.data.phone, body.data.isActive]); return { branch: branch.rows[0] }; }); if ("error" in result) return res.status(result.code).json({ error: result.error, code: result.errorCode }); res.status(201).json(toApiResponse(result.branch)); } catch (err: any) { logger.error({ err: err.message, tenantId: req.tenantId }, "Branch creation failed"); res.status(500).json({ error: "Cabang gagal dibuat." }); } }
