import React, { useEffect, useState } from "react";
import {
  ArrowRight,
  Banknote,
  BarChart3,
  Boxes,
  Check,
  ChevronDown,
  CircleCheck,
  Menu,
  MessageSquare,
  MonitorSmartphone,
  ShieldCheck,
  Users,
  Wrench,
  X,
  Zap,
} from "lucide-react";
import { LoginPage } from "./LoginPage";
import { useSaaS } from "../context/SaaSContext";

type BillingPlan = {
  tier: string;
  name: string;
  priceMonthly: number;
  features: string[];
};

const modules = [
  { icon: Wrench, title: "Servis", desc: "Kelola seluruh siklus servis dalam satu alur.", tone: "bg-indigo-50 text-indigo-600", features: ["Tiket & SPK", "Knowledge base", "Kalkulator biaya", "QC scoring", "Klaim garansi", "Field service", "Rental", "QR tracker"] },
  { icon: Banknote, title: "POS & Pembayaran", desc: "Transaksi cepat dan pencatatan kas yang rapi.", tone: "bg-emerald-50 text-emerald-600", features: ["Kasir", "Shift kasir", "Riwayat transaksi", "Marketplace hub"] },
  { icon: Boxes, title: "Inventory", desc: "Kontrol persediaan lintas gudang dan cabang.", tone: "bg-amber-50 text-amber-600", features: ["Stok", "Transfer stok", "Lokasi gudang", "Trade-in", "Cannibal", "Sparepart kecil", "Aset", "Konsinyasi", "Purchase order"] },
  { icon: BarChart3, title: "Keuangan", desc: "Angka bisnis siap dibaca tanpa laporan manual.", tone: "bg-sky-50 text-sky-600", features: ["Chart of accounts", "Buku besar", "Laporan keuangan"] },
  { icon: Users, title: "HR & CRM", desc: "Kelola tim dan hubungan pelanggan lebih dekat.", tone: "bg-violet-50 text-violet-600", features: ["Absensi", "Payroll", "Komisi", "Kasbon", "Pipeline", "Pelanggan", "Marketing"] },
  { icon: ShieldCheck, title: "Kontrol & Integrasi", desc: "Operasional aman, terhubung, dan mudah diawasi.", tone: "bg-rose-50 text-rose-600", features: ["Audit log", "Fraud alert", "WhatsApp", "Workflow", "RBAC", "Developer API", "Loyalty"] },
];

const testimonials = [
  { initials: "AR", name: "Andi R.", role: "Pemilik bengkel komputer", quote: "Mantapki tawwa ini web dipakai. Tiket servis, stok, sama kasir langsung nyambung, jadi tidak perlu catat dua kali." },
  { initials: "FN", name: "Fajar N.", role: "Pengelola servis gadget", quote: "Keren webnya. Saya sudah gunakan untuk pantau teknisi dan status servis, pelanggan juga lebih gampang dikabari." },
  { initials: "MI", name: "Muh. I.", role: "Pemilik toko sparepart", quote: "Enak dipakai, stok masuk keluar kelihatan jelas. Laporan usaha juga tidak perlu lagi kumpul manual, mantapki." },
];

const formatPrice = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);

export const LandingPage: React.FC = () => {
  const { isAuthenticated } = useSaaS();
  const [showLogin, setShowLogin] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [plans, setPlans] = useState<BillingPlan[]>([]);

  useEffect(() => {
    fetch("/api/billing/public-plans")
      .then((response) => response.ok ? response.json() : Promise.reject())
      .then((data) => setPlans(Array.isArray(data) ? data : []))
      .catch(() => setPlans([]));
  }, []);

  if (showLogin) return <LoginPage onBack={() => setShowLogin(false)} />;

  const scrollTo = (id: string) => {
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
    setMenuOpen(false);
  };

  return (
    <main className="min-h-screen overflow-x-hidden bg-slate-50 text-slate-900" id="landing-page">
      <div className="pointer-events-none fixed inset-x-0 top-0 h-[720px] bg-[radial-gradient(circle_at_18%_5%,rgba(99,102,241,.20),transparent_32%),radial-gradient(circle_at_82%_10%,rgba(34,211,238,.16),transparent_28%)]" />
      <nav className="sticky top-0 z-30 border-b border-slate-200/70 bg-white/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6">
          <button onClick={() => scrollTo("landing-page")} className="flex items-center gap-2.5 font-black tracking-tight" aria-label="FixDev beranda"><span className="grid h-9 w-9 place-items-center rounded-xl bg-accent text-white shadow-lg shadow-accent/20"><Wrench className="h-4 w-4" /></span><span>FixDev</span></button>
          <div className="hidden items-center gap-6 md:flex"><button onClick={() => scrollTo("fitur")} className="text-xs font-bold text-slate-600 hover:text-accent">Fitur</button><button onClick={() => scrollTo("cara-kerja")} className="text-xs font-bold text-slate-600 hover:text-accent">Cara kerja</button><button onClick={() => scrollTo("testimoni")} className="text-xs font-bold text-slate-600 hover:text-accent">Testimoni</button><button onClick={() => scrollTo("paket")} className="text-xs font-bold text-slate-600 hover:text-accent">Paket</button><button onClick={() => setShowLogin(true)} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-black text-slate-700">{isAuthenticated ? "Buka dashboard" : "Masuk"}</button><button onClick={() => setShowLogin(true)} className="rounded-xl bg-accent px-4 py-2 text-xs font-black text-white">Mulai sekarang <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></button></div>
          <button onClick={() => setMenuOpen((open) => !open)} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white md:hidden" aria-label="Buka menu">{menuOpen ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</button>
        </div>
        {menuOpen && <div className="grid gap-1 border-t border-slate-100 bg-white p-3 md:hidden">{[["fitur", "Fitur"], ["cara-kerja", "Cara kerja"], ["testimoni", "Testimoni"], ["paket", "Paket"]].map(([id, label]) => <button key={id} onClick={() => scrollTo(id)} className="rounded-xl px-3 py-2 text-left text-xs font-bold">{label}</button>)}<button onClick={() => setShowLogin(true)} className="rounded-xl bg-accent px-3 py-2 text-left text-xs font-bold text-white">Masuk atau daftar</button></div>}
      </nav>

      <section className="relative z-10 mx-auto grid max-w-6xl items-center gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:py-24">
        <div><div className="mb-5 inline-flex items-center rounded-full border border-indigo-100 bg-white px-3 py-1.5 text-[10px] font-black uppercase tracking-wider text-accent shadow-sm">Sistem bisnis servis modern</div><h1 className="max-w-2xl text-4xl font-black leading-[1.03] tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Satu kendali untuk <span className="text-accent">seluruh bisnis servis.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-slate-600 sm:text-base">Servis, kasir, stok, keuangan, tim, pelanggan, dan komunikasi bekerja dalam satu sistem. Pemilik dapat fokus bertumbuh, tim bekerja lebih cepat.</p><div className="mt-7 flex flex-col gap-2 sm:flex-row"><button onClick={() => setShowLogin(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-accent px-5 py-3 text-xs font-black text-white shadow-lg shadow-accent/20">Daftarkan bisnis <ArrowRight className="h-4 w-4" /></button><button onClick={() => scrollTo("fitur")} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-xs font-black text-slate-700">Jelajahi fitur <ChevronDown className="h-4 w-4" /></button></div><div className="mt-8 grid max-w-xl grid-cols-3 gap-3 border-t border-slate-200 pt-5"><div><p className="text-lg font-black">35+</p><p className="text-[10px] font-bold text-slate-500">Subfitur bisnis</p></div><div><p className="text-lg font-black">Multi</p><p className="text-[10px] font-bold text-slate-500">Cabang & gudang</p></div><div><p className="text-lg font-black">RBAC</p><p className="text-[10px] font-bold text-slate-500">Akses per peran</p></div></div></div>
        <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-4 -z-10 rounded-[2rem] bg-gradient-to-br from-indigo-300/60 to-cyan-200/50 blur-2xl" /><div className="overflow-hidden rounded-3xl border border-white/80 bg-white p-3 shadow-2xl shadow-indigo-200/60"><div className="flex items-center justify-between border-b border-slate-100 pb-3"><div className="flex gap-1.5"><i className="h-2 w-2 rounded-full bg-rose-400" /><i className="h-2 w-2 rounded-full bg-amber-400" /><i className="h-2 w-2 rounded-full bg-emerald-400" /></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black text-emerald-700">Sistem aktif</span></div><div className="mt-3 grid gap-3 sm:grid-cols-[.9fr_1.1fr]"><aside className="rounded-2xl bg-slate-950 p-3 text-slate-300"><div className="flex items-center gap-2 text-xs font-black text-white"><span className="grid h-6 w-6 place-items-center rounded-lg bg-indigo-500"><Wrench className="h-3 w-3" /></span>Toko Anda</div><div className="mt-5 space-y-1 text-[10px] font-bold"><p className="rounded-lg bg-white/10 px-2 py-1.5 text-white">Ringkasan</p><p className="px-2 py-1.5">Servis</p><p className="px-2 py-1.5">Kasir</p><p className="px-2 py-1.5">Stok</p><p className="px-2 py-1.5">Laporan</p></div></aside><div className="space-y-3"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold text-slate-500">Ringkasan operasional</p><p className="text-sm font-black">Bisnis hari ini</p></div><span className="grid h-8 w-8 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Zap className="h-4 w-4" /></span></div><div className="grid grid-cols-2 gap-2"><div className="rounded-xl border p-2.5"><p className="text-[9px] font-bold text-slate-500">Servis aktif</p><p className="mt-1 text-lg font-black">24</p></div><div className="rounded-xl border p-2.5"><p className="text-[9px] font-bold text-slate-500">Transaksi</p><p className="mt-1 text-lg font-black">48</p></div></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black">Tiket terbaru</p><div className="mt-2 flex items-center gap-2 rounded-lg bg-white p-2"><span className="grid h-6 w-6 place-items-center rounded-lg bg-amber-50 text-amber-600"><MonitorSmartphone className="h-3 w-3" /></span><div className="flex-1"><p className="text-[9px] font-black">Perangkat pelanggan</p><p className="text-[8px] font-bold text-slate-500">Menunggu diagnosa</p></div></div></div></div></div></div></div>
      </section>

      <section id="fitur" className="relative mx-auto max-w-6xl px-4 py-16 sm:px-6"><div className="max-w-2xl"><p className="text-[10px] font-black uppercase tracking-widest text-accent">Ekosistem lengkap</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Bukan cuma modul. Semua pekerjaan penting ada di dalamnya.</h2></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{modules.map((module) => <article key={module.title} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${module.tone}`}><module.icon className="h-5 w-5" /></span><h3 className="mt-4 text-base font-black">{module.title}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{module.desc}</p><div className="mt-4 flex flex-wrap gap-1.5">{module.features.map((feature) => <span key={feature} className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[9px] font-bold text-slate-600">{feature}</span>)}</div></article>)}</div></section>

      <section id="cara-kerja" className="bg-slate-950 py-16 text-white"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-[10px] font-black uppercase tracking-widest text-cyan-300">Alur bisnis terhubung</p><h2 className="mt-2 text-3xl font-black">Dari perangkat masuk sampai laba tercatat.</h2><p className="mt-3 text-xs leading-5 text-slate-300">Setiap bagian mendapat informasi yang dibutuhkan. Pemilik melihat gambaran bisnis tanpa mengejar laporan manual.</p></div><div className="grid gap-3 sm:grid-cols-3">{[["01", "Terima & diagnosa", "Pelanggan, keluhan, foto, estimasi, dan SPK tersimpan."], ["02", "Kerjakan & pantau", "Teknisi, sparepart, QC, garansi, dan notifikasi terhubung."], ["03", "Bayar & analisis", "Invoice, kasir, stok, komisi, dan laporan diperbarui."]].map(([number, title, desc]) => <div key={number} className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xl font-black text-cyan-300">{number}</p><h3 className="mt-8 text-sm font-black">{title}</h3><p className="mt-2 text-[11px] leading-5 text-slate-300">{desc}</p></div>)}</div></div></section>

      <section id="testimoni" className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><div className="mx-auto max-w-2xl text-center"><p className="text-[10px] font-black uppercase tracking-widest text-accent">Contoh testimonial pengguna beta</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Pelaku usaha Makassar bilang mantapki.</h2><p className="mt-3 text-xs text-slate-500">Contoh konten; ganti dengan testimonial terverifikasi sebelum publikasi.</p></div><div className="mt-8 grid gap-4 lg:grid-cols-3">{testimonials.map((item) => <figure key={item.name} className="group relative rounded-3xl border border-slate-200 bg-white p-8 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="absolute -top-4 left-1/2 h-8 w-8 -translate-x-1/2 rounded-full border-4 border-white bg-gradient-to-br from-indigo-600 to-purple-600 flex items-center justify-center text-xs font-bold text-white">{item.initials}</div><blockquote className="mt-6 text-sm leading-7 text-slate-700 text-center">""" {item.quote} """</blockquote><figcaption className="mt-8 flex flex-col items-center gap-2 text-center"><strong className="text-sm font-black text-slate-900">{item.name}</strong><span className="text-[11px] text-slate-600">{item.role}</span></figcaption></figure>)}</div></section>

      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><div className="mx-auto max-w-2xl text-center"><p className="text-[10px] font-black uppercase tracking-widest text-accent">Tampilan fitur</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Lihat cara FixDev bekerja.</h2><p className="mt-3 text-xs text-slate-500">Mockup orisinal berbasis antarmuka aplikasi, tanpa aset eksternal.</p></div><div className="mt-8 grid gap-4 lg:grid-cols-3">{[{ title: "Meja servis", icon: Wrench, rows: [["Tiket baru", "Menunggu diagnosa"], ["QC perangkat", "Dalam pemeriksaan"], ["Serah terima", "Siap diambil"]] }, { title: "Kasir & stok", icon: Banknote, rows: [["Transaksi hari ini", "48 transaksi"], ["Stok menipis", "6 produk"], ["Transfer gudang", "2 proses"]] }, { title: "Kinerja bisnis", icon: BarChart3, rows: [["Pendapatan", "Tercatat otomatis"], ["Komisi teknisi", "Siap dihitung"], ["Laporan", "Siap ditinjau"]] }].map((preview) => <article key={preview.title} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-200/50"><div className="flex items-center gap-2 border-b border-slate-100 bg-slate-950 px-4 py-3 text-xs font-black text-white"><preview.icon className="h-4 w-4 text-cyan-300" />{preview.title}</div><div className="space-y-2 p-4">{preview.rows.map(([label, value], index) => <div key={label} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${index === 0 ? "bg-emerald-500" : index === 1 ? "bg-amber-500" : "bg-indigo-500"}`} /><span className="text-[10px] font-black">{label}</span></div><span className="text-[9px] font-bold text-slate-500">{value}</span></div>)}</div></article>)}</div></section>

      <section className="border-y border-slate-200 bg-white py-16"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid gap-4 md:grid-cols-3">{[{ title: "Data penyewa terisolasi", text: "Ruang data tiap bisnis dipisahkan dan akses dibatasi berdasarkan peran.", icon: ShieldCheck }, { title: "Onboarding terarah", text: "Buat toko, atur cabang, undang tim, lalu aktifkan alur kerja yang dibutuhkan.", icon: Users }, { title: "Dukungan operasional", text: "Tim mendapat bantuan saat konfigurasi, migrasi, dan penggunaan fitur bisnis.", icon: MessageSquare }].map((item) => <article key={item.title} className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><item.icon className="h-6 w-6 text-accent" /><h3 className="mt-4 text-sm font-black">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{item.text}</p></article>)}</div></div></section>

      <section className="mx-auto max-w-4xl px-4 py-16 sm:px-6"><div className="text-center"><p className="text-[10px] font-black uppercase tracking-widest text-accent">FAQ</p><h2 className="mt-2 text-3xl font-black tracking-tight">Pertanyaan sebelum mulai.</h2></div><div className="mt-8 space-y-3">{[["Berapa lama proses setup?", "Setup awal dilakukan bertahap: membuat toko, cabang, pengguna, hak akses, lalu modul operasional."], ["Apakah bisa dipakai banyak cabang?", "Bisa. Batas cabang dan pengguna mengikuti paket aktif dari konfigurasi billing."], ["Apakah data tiap penyewa bercampur?", "Tidak. Sistem menerapkan ruang data penyewa dan pembatasan akses per peran."], ["Apakah paket dapat berubah?", "Bisa. Nama, harga, batas, dan fitur paket di landing page mengikuti konfigurasi billing terbaru."], ["Bagaimana mendapat bantuan?", "Daftar atau masuk untuk memulai onboarding dan menghubungi dukungan melalui kanal yang tersedia di aplikasi."]].map(([question, answer]) => <details key={question} className="group rounded-2xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer list-none text-xs font-black">{question}<ChevronDown className="float-right h-4 w-4 transition group-open:rotate-180" /></summary><p className="mt-3 pr-6 text-xs leading-5 text-slate-600">{answer}</p></details>)}</div></section>

      <section id="paket" className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><div className="mx-auto max-w-2xl text-center"><p className="text-[10px] font-black uppercase tracking-widest text-accent">Paket langganan</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Paket mengikuti konfigurasi billing.</h2></div>{plans.length > 0 ? <div className="mt-8 grid gap-4 lg:grid-cols-3">{plans.map((plan, index) => <article key={plan.tier} className={`rounded-3xl border bg-white p-5 ${index === 1 ? "border-accent shadow-xl shadow-accent/10" : "border-slate-200"}`}><h3 className="text-sm font-black">{plan.name}</h3><p className="mt-3 text-2xl font-black">{formatPrice(plan.priceMonthly)}<span className="text-[10px] text-slate-500"> / bulan</span></p><button onClick={() => setShowLogin(true)} className={`mt-4 w-full rounded-xl py-2.5 text-xs font-black ${index === 1 ? "bg-accent text-white" : "border border-slate-200"}`}>Pilih paket</button><ul className="mt-5 space-y-2">{plan.features.map((feature) => <li key={feature} className="flex gap-2 text-[11px] font-bold text-slate-700"><CircleCheck className="h-3.5 w-3.5 shrink-0 text-emerald-600" />{feature}</li>)}</ul></article>)}</div> : <div className="mt-8 rounded-3xl border border-slate-200 bg-white p-8 text-center"><p className="text-sm font-black">Paket sedang dimuat</p><p className="mt-2 text-xs text-slate-500">Silakan masuk untuk melihat paket langganan terbaru.</p></div>}</section>

      <section className="mx-auto max-w-6xl px-4 pb-16 sm:px-6"><div className="rounded-3xl bg-gradient-to-br from-indigo-600 to-slate-950 p-8 text-white sm:p-10"><div className="flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-[10px] font-black uppercase tracking-widest text-cyan-200">Siap bertumbuh?</p><h2 className="mt-2 text-3xl font-black">Bawa seluruh operasional ke satu sistem.</h2><p className="mt-2 text-xs text-indigo-100"><Check className="mr-1 inline h-3 w-3" />Mulai konfigurasi bisnis tanpa input kartu di awal.</p></div><button onClick={() => setShowLogin(true)} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-xs font-black text-slate-950">Daftarkan bisnis <ArrowRight className="h-4 w-4" /></button></div></div></section>

      <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-4 py-6 text-[10px] font-bold text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-6"><span>© 2026 FixDev</span><span>Operasional lebih rapi, bisnis lebih siap tumbuh.</span></div></footer>
    </main>
  );
};
